project:
  type: website

website:
  title: "The Finnish Society for Bioinformatics"
  favicon: images/round_logo.jpg
  navbar:
    toggle-position: right
    logo: images/logo.png
    title: false
    right:
      - href: pages/about.qmd
      - href: pages/events.qmd
      - href: pages/jobs.qmd
      - href: pages/collaborators.qmd
        text: Collaborators
      - href: pages/research-highlights.qmd
        text: Research Highlights
      - href: pages/bioinformatics-webinars.qmd
        text: Bionformatics Webinars
      - href: pages/join-the-society.qmd
        text: Join the Society
      - href: pages/bioinformatics-day-2026.qmd
        text: Bioinformatics Day 2026

  page-footer:
    left: |
      ![](../images/logo.png){width=30%}
      We would love to hear from you! Send us an email: fsfbioinf@gmail.com
    center: Copyright &copy; 2026 The Finnish Society for Bioinformatics
    right: "Follow us on [Linkedin](https://www.linkedin.com/company/finnish-society-for-bioinformatics)"

format:
  html:
    page-layout: full
    theme:
      - cosmo
      - styles.scss
    toc: true
