project:
  type: website

execute:
  freeze: auto

website:
  title: "The Finnish Society for Bioinformatics"
  open-graph: true
  favicon: images/round_logo.jpg
  image: images/logo_white.jpg
  description: "Finnish Society for Bioinformatics website"
  navbar:
    toggle-position: right
    logo: images/logo_white.jpg
    logo-alt: "Finnsh Society for Bionformatics"
    title: false
    right:
      - href: pages/about.qmd
      - href: pages/events.qmd
      - href: pages/jobs.qmd
      - href: pages/collaborators.qmd
        text: Collaborators
      - href: pages/research-highlights.qmd
        text: Research Highlights
      - href: pages/bioinformatics-webinars.qmd
        text: Bionformatics Webinars
      - href: pages/join-the-society.qmd
        text: Join the Society
      - href: pages/bioinformatics-day-2026.qmd
        text: Bioinformatics Day 2026

  page-footer:
    left: |
      We would love to hear from you! Send us an email: fsfbioinf@gmail.com
    center: Copyright &copy; 2026 The Finnish Society for Bioinformatics
    right:
      - href: https://github.com/Finnish-Society-for-Bioinformatics
        icon: github
        aria-label: GitHub
      - href: https://www.linkedin.com/company/finnish-society-for-bioinformatics
        icon: linkedin
        aria-label: LinkedIn
      - href: https://bioinffi.slack.com/
        icon: slack
        aria-label: Slack

page-navigation: true
back-to-top-navigation: false

format:
  html:
    page-layout: full
    theme:
      - cosmo
      - styles.scss
    toc: true
